version: '3.4'
services:
  api:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports: 
      - 5000:5000
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    ports:
      - 3645:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  frontend:
    build:
      context: ./frontend
    environment:
      ENV: development       # Choose one: development/production
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    depends_on:
      - server-backend
  server-backend:
    build: 
      context: ./server-backend
    # environment:
    #   API_HOST: ''          # Change this to any host you like; remove to set host at http://localtunnel.me
    #   API_SUBDOMAIN: ''     # Change this to any subdomain you like; Remove to generate a random subdomain.
    volumes:
      - ./server-backend:/server-backend
      - ./frontend/src/_Utils:/server-backend/output
    depends_on:
      - api
  server-frontend:
    build: 
      context: ./server-frontend
    # environment:
    #   WEB_HOST: ''          # Change this to any host you like; remove to set host at http://localtunnel.me
    #   WEB_SUBDOMAIN: ''     # Change this to any subdomain you like; Remove to generate a random subdomain.
    volumes:
      - ./server-frontend:/server-frontend
    depends_on:
      - frontend
      