version: '2'
services:
  api:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports: 
      - 5000:5000 # API server
    depends_on:
      - postgres
  postgres:
    image: postgres:11.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app-db
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    ports:
      - 3645:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - api